import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloClient, ApolloProvider, InMemoryCache } from "@apollo/client";
import { useMemo } from "react";
// import {createApolloClient} from '../graphQl/appolloClient'
import { ApolloWrapper } from "@/graphQl/appolloWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Graphql-learn",
  description: "Generated by create next app",
};
// let URL = process.env.NEXT_PUBLIC_BASE_URL || "";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
//   const client =  new ApolloClient ({
//     uri:URL,
//     cache: new InMemoryCache()
//  })
  // const appolloClient = useMemo(()=>createApolloClient(),[])
  return (

   <>
    <html lang="en">
  
      <body className={inter.className}> 
      <ApolloWrapper>{children}</ApolloWrapper>
        </body>
    </html>
   </>
  );
}
